/*<license>
  Copyright 2004, PeopleWare n.v.
  NO RIGHTS ARE GRANTED FOR THE USE OF THIS SOFTWARE, EXCEPT, IN WRITING,
  TO SELECTED PARTIES.
</license>*/
package be.peopleware.persistence_II.sql;


import java.sql.SQLException;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import be.peopleware.bean_V.ConstraintException;
import be.peopleware.bean_V.DuplicateKeyException;
import be.peopleware.bean_V.PropertyException;
import be.peopleware.persistence_II.PersistentBean;


/**
 * Growing implementation for handling general {@link SQLException SQLExceptions}
 * generated by MySQL.
 *
 * @author    Jan Dockx
 * @author    PeopleWare n.v.
 */
public class MySqlSqlExceptionHandler implements SqlExceptionHandler {

  /* <section name="Meta Information"> */
  //------------------------------------------------------------------

  /** {@value} */
  public static final String CVS_REVISION = "$Revision$";
  /** {@value} */
  public static final String CVS_DATE = "$Date$";
  /** {@value} */
  public static final String CVS_STATE = "$State$";
  /** {@value} */
  public static final String CVS_TAG = "$Name$";

  /* </section> */



  /* <construction> */
  //------------------------------------------------------------------

  // default constructor

  /* </construction> */


  private static final Log LOG = LogFactory.getLog(MySqlSqlExceptionHandler.class);


  /**
   * Return a {@link PropertyException} wrapping <code>sqlException</code>
   * if you find the latter of a semantic nature. If not, return <code>null</code>.
   *
   * If the message of the given sql exception contains the string
   *   "Duplicate key or integrity constraint violation,  message from server: \"Duplicate entry"
   * or
   *   "Duplicate entry"
   * return a {@link DuplicateKeyException}.
   *
   * If the message of the given sql exception contains the string
   * "Duplicate key or integrity constraint violation,  "
   *             + "message from server: \"Cannot delete or update a "
   *             + "parent row: a foreign key constraint fails\""
   * return a {@link ConstraintException}.
   *
   * Otherwise, return null.
   */
  public PropertyException handle(final SQLException sqlExc, final PersistentBean pb) {
    assert sqlExc != null;
    if (sqlExc.getMessage()
              .indexOf("Duplicate key or integrity constraint violation,  "
                       + "message from server: \"Duplicate entry") >= 0
        || sqlExc.getMessage().indexOf("Duplicate entry") >= 0) {
      // WATCH OUT: SQL Error message contains 'dual space' after ','.
      DuplicateKeyException dkExc = new DuplicateKeyException(pb,
                                                              null,
                                                              "VALUE_NOT_UNIQUE",
                                                              sqlExc);
      LOG.debug("recognized MySQL duplicate key exception", dkExc);
      return dkExc;
    }
    if (sqlExc.getMessage()
        .indexOf("Duplicate key or integrity constraint violation,  "
                 + "message from server: \"Cannot delete or update a "
                 + "parent row: a foreign key constraint fails\"") >= 0) {
      // WATCH OUT: SQL Error message contains 'dual space' after ','.
      ConstraintException cExc = new ConstraintException(pb,
                                                         null,
                                                         "CONSTRAINT_FAILURE",
                                                         sqlExc);
      LOG.debug("recognized MySQL constraint violation exception", cExc);
      return cExc;
    }
    return null;
  }

}
